### ISSUE TITLE
Graphical Glitches on Zero Escape : Virtue's Last Reward with hardware shaders enabled

### ISSUE THREAD

**Issue by mzn928** [weihuoya/citra#500]
Description: While running Zero Escape : Virtue's Last Reward With hardware shaders enabled, 3D models are glitched and a black texture covers them as seen in the screen shots. Enabling Accurate Multiplication (on Accurate mode) reduces the black texture but it is still present even with that option.
However disabling Hardware shaders fixes the issue but the performance is not optimal for playing (10 fps or less)
Changing other options seems to not affect this issue at all (for example enabling new 3ds mode)

Screenshots:
### With Hardware Shader enabled and Accurate Multiplication Off:
![image](https://user-images.githubusercontent.com/16765128/160844314-7eb4d45d-00db-4744-a9e4-be3e259f3906.png)

### With Hardware Shader enabled and Accurate Multiplication On (Accurate mode):
![image](https://user-images.githubusercontent.com/16765128/160844276-73e30a29-2e94-4097-bdd7-7c7721bbb717.png)

### With Hardware Shader turned off:
![image](https://user-images.githubusercontent.com/16765128/160844212-5bdff5eb-9794-4a50-9e62-be468a9d5361.png)

Device Info:
Device: Poco X3 Pro
CPU: SD 860
GPU: Adreno 640
RAM: 8 GB
Citra Build: 20220225

Let me know if i can provide any help or info. i'll be glad

**Comment by Tappy-tech** [comment]
Enabling New 3DS mode won't speed up and fix slow speed problem. What options besides New 3DS mode you have tried to fix it? (And Hardware Shader with Accurate Multiplication, of course)

**Comment by mzn928** [comment]
> Enabling New 3DS mode won't speed up and fix slow speed problem. What options besides New 3DS mode you have tried to fix it? (And Hardware Shader with Accurate Multiplication, of course)

As i said in the first comment nothing beside enabling or disabling hardware shader seems to affect the graphical glitch.
as for the slow performance when i disable hardware shader, i tried the obvious stuff (like making sure dual core is enabled, cpu jit) and had no luck either. im open to any suggestion as to what should i try next.

**Comment by Tappy-tech** [comment]
> As i said in the first comment nothing beside enabling or disabling hardware shader seems to affect the graphical glitch. as for the slow performance when i disable hardware shader, i tried the obvious stuff (like making sure dual core is enabled, cpu jit) and had no luck either. im open to any suggestion as to what should i try next.

Try enabling FMV Hack, Skip Slow Draw, Skip Copy Texture, CPU Usage Limit. If none works, try resolution hack.

**Comment by mzn928** [comment]
> > As i said in the first comment nothing beside enabling or disabling hardware shader seems to affect the graphical glitch. as for the slow performance when i disable hardware shader, i tried the obvious stuff (like making sure dual core is enabled, cpu jit) and had no luck either. im open to any suggestion as to what should i try next.
> 
> Try enabling FMV Hack, Skip Slow Draw, Skip Copy Texture, CPU Usage Limit. If none works, try resolution hack.

thanks for the reply. i tried the above mentioned settings. Skip Slow Draw renders the screen black and doesn't show anything. other options didn't have any noticeable performance difference. and resolution hack actually made the performance worse (went from 10 fps at the opening scene to 6)

**Comment by Tappy-tech** [comment]
CPU Usage + FMV Hack?

**Comment by mzn928** [comment]
> CPU Usage + FMV Hack?

Do you mean enabling cpu usage limit and fmv hack? I did that and performance didn't change

**Comment by BenzLeung** [comment]
same game same issue.

My device:
Oneplus 10pro
Android 12 (ColorOS 12)
CPU: Snapdragon 8
GPU: Adreno 730
RAM: 12 GB
Citra_MMJ_20220225 (5db21215d)

**Comment by BenzLeung** [comment]
WTF my Newbility Big Boss!!
WTF my Badass Cool guy!!!
卧槽大佬NB！！！
Fixed in the release just a moment ago!!!
Citra_MMJ_20220419 very very cool!!!
感谢大佬！膜拜大佬！

**Comment by DavidAriyan** [comment]
Super wow. This long almost forgotten bugs finally has been fixed. Thank you for your hard work  👍👍❤️. This is my favorite game on the 3ds.

**Comment by BenzLeung** [comment]
Oh no.
The issue come back in ver.Citra_MMJ_20220420...
What is the matter?

**Comment by DavidAriyan** [comment]
The issue come back! I Just use the previous version instead.

**Comment by mzn928** [comment]
So the April 19th version indeed fixed the glitch but I feel like performance is a little worse than before when the glitch was still present. 
Here are the settings which has worked the best for me so far:
Hardware shader with fast Multiplication
Sepertate shader
New 3ds mode off (game will freeze for me with this)
Fmv hack on (without this audio is really stuttery)
1x render scale

Enabling post processing effects like fxaa also makes the game freeze randomly.
And sometimes instead of the usual game audio some noise gets played for a split second

**Comment by BenzLeung** [comment]
> 

Thank you for the settings. I will set & try it with Citra_MMJ_20220419.
