### ISSUE TITLE
Heat effect bug in mhxx

### ISSUE THREAD

**Issue by endrare** [weihuoya/citra#800]
Map location Dunes

![Screenshot_2023-06-11-08-30-57-112_com antutu ABenchMark](https://github.com/weihuoya/citra/assets/33047223/c26f9d3e-bc5d-4723-9bfa-af108bf07ceb)

**Comment by endrare** [comment]
Fixed build [20230626](https://github.com/weihuoya/citra/releases/tag/20230626)
![Screenshot_2023-06-26-12-11-16-480_com antutu ABenchMark](https://github.com/weihuoya/citra/assets/33047223/93d0bead-b033-4bd8-ab35-f282d88aef68)

**Comment by endrare** [comment]
After the update to [20230627] the problem came back

![Screenshot_2023-06-27-15-06-21-798_org citra emu](https://github.com/weihuoya/citra/assets/33047223/79dfdbd9-8e98-4cae-8bee-abb6deee0814)

**Comment by Deka710** [comment]
yeah its broken again in latest build
![Screenshot_2023-06-13-15-26-09-029_org citra emu](https://github.com/weihuoya/citra/assets/97207704/5de6e2b8-dfbc-4600-8316-a16e2d1adca3)
![Screenshot_2023-06-13-15-15-05-561_org citra emu](https://github.com/weihuoya/citra/assets/97207704/3cf2b5f4-eb78-4471-827f-c167a050d8d5)

**Comment by Deka710** [comment]
still broken in latest build, the last working version is 20 april 2023 build
